<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Compumatrice" ignored="5" name="Default test" tests="1" failures="1" timestamp="10 May 2017 10:05:13 GMT" time="0.078" errors="0">
  <testcase name="All_Sections_Comments" time="0.047" classname="test_collection.Report_Writing_Tests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at test_cases.Comments_Tab_Section.Select_Comments_Dropdown_Option(Comments_Tab_Section.java:78)
	at test_cases.Comments_Tab_Section.All_Sections_Comments(Comments_Tab_Section.java:206)
	at test_collection.Report_Writing_Tests.All_Sections_Comments(Report_Writing_Tests.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- All_Sections_Comments -->
  <testcase name="Add_Edit_Comments" time="0.0" classname="test_collection.Report_Writing_Tests">
    <ignored/>
  </testcase> <!-- Add_Edit_Comments -->
  <testcase name="Add_Address" time="0.0" classname="test_collection.Report_Writing_Tests">
    <ignored/>
  </testcase> <!-- Add_Address -->
  <testcase name="Drag_Drop_Library" time="0.0" classname="test_collection.Report_Writing_Tests">
    <ignored/>
  </testcase> <!-- Drag_Drop_Library -->
  <testcase name="startbrowser" time="0.0" classname="test_collection.Report_Writing_Tests">
    <ignored/>
  </testcase> <!-- startbrowser -->
  <testcase name="Login" time="0.0" classname="test_collection.Report_Writing_Tests">
    <ignored/>
  </testcase> <!-- Login -->
</testsuite> <!-- Default test -->
